[GPAW]
xc='PBE'
mode= {name='fd'}
#eigensolver= {name='dav',niter=1}
#occupations= {name='fermi-dirac',width=0.05,fixmagmom=tru
gpts = [20,20,20]
symmetry = 'off'

[VASP]
xc = 'pbesol'
encut = 520
ediff = 1e-05
ediffg = -0.03
algo = 'all'
prec = 'accurate'
sigma = 0.05
ibrion = 2
isif = 3
ismear = 0
ispin = 2
nelmin = 8
nelm = 400
lmaxmix = 4
nsw = 0
lorbit = 12
npar = 1
kpar = 1
lreal = 'auto'
gamma = true
ldau = true
system = 'ni'
ncore = 4
istart = 0
isym = 0
lcharg = false
lwave = true
kspacing = 0.3
command = 'mpirun vasp_std'
setups = 'materialsproject'
nupdown = 0
ldau_luj = {'Fe'= {'L'= 2, 'U'= 5.3, 'J'= 0}}
